app:
  name: "ExchangeApp"
  port: 3000

observability:
  enable_pprof: false
  slow_request_threshold_ms: 500

auth:
  jwt_secret: "secret"

database:
  dsn: "user:password@tcp(127.0.0.1:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

storage:
  upload_dir: "uploads"
